V99999Z:
  name: V99999Z
  system: geds
  location:
    string: 1
    position: 1
  daq:
    rawid: 1

S9999T:
  name: S9999T
  system: spms
  location:
    barrel: 1
    fiber: S9999
    position: top
  daq:
    rawid: 5000
